config/routes.rb
Adslapme::Application.routes.draw do

  resources :users
  resources :albums do
    collection do
      get :import_facebook_photos
    end
  end
  resources :pictures

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  
  match '/submit_pic',  :to => 'users#submit_pic'
  match '/capture_pic',  :to => 'users#capture_pic'
  match '/startup_weekend',  :to => 'users#show_sw_pics'
  

  root :to => 'pages#home'

  resources :sessions, :only => [:new, :create] do
    collection do
      get :facebook_session_create
    end
  end

end

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.haml
:javascript
  if (document.all||document.getElementById)
  {
    document.write('<style id="tmpStyle" type="text/css">#pic {-moz-opacity:0.00;filter:alpha(opacity=0);opacity:0;-khtml-opacity:0;}<\/style>')
  	var objG;
  	var _startDegree = 40;
  	var degree = _startDegree;
  	var fadeAssist = 0;
  	var imgArray = [
  					"#{Settings.app_url}/images/woman1.jpg",
  					"#{Settings.app_url}/images/woman2.jpg",
  					"#{Settings.app_url}/images/woman3.jpg",
  					"#{Settings.app_url}/images/woman5.jpg"
  				   ];
  	var currImgIdx = 0;
  }

  function fadeInPic(obj)
  {
  	objG=obj
  	if (!document.getElementById&&!document.all) return;
  	var tS=document.all? document.all['tmpStyle'] : document.getElementById('tmpStyle')
  	if (degree<100)
  	{
  		degree+=5
  		if (objG.filters&&objG.filters[0]&&fadeAssist)
  			fadeAssist(objG, degree)
  		else if (typeof objG.style.MozOpacity=='string')
  			objG.style.MozOpacity=degree/101
  		else if (typeof objG.style.KhtmlOpacity=='string')
  			objG.style.KhtmlOpacity=degree/100
  		else if (typeof objG.style.opacity=='string'&&!objG.filters)
  			objG.style.opacity=degree/101
  		else
  			tS.disabled=true
  		setTimeout("fadeInPic(objG)", 50);
  	}
  	else
  	{
  	tS.disabled=true
  		setTimeout("fadeOutPic(objG)", 2000);
  	}
  	//tS.disabled=true
  }

  function fadeOutPic(obj)
  {
  	objG=obj
  	if (!document.getElementById&&!document.all) return;
  	var tS=document.all? document.all['tmpStyle'] : document.getElementById('tmpStyle')
  	if (degree>_startDegree)
  	{
  		degree-=5
  		if (objG.filters&&objG.filters[0]&&fadeAssist)
  			fadeAssist(objG, degree)
  		else if (typeof objG.style.MozOpacity=='string')
  			objG.style.MozOpacity=degree/101
  		else if (typeof objG.style.KhtmlOpacity=='string')
  			objG.style.KhtmlOpacity=degree/100
  		else if (typeof objG.style.opacity=='string'&&!objG.filters)
  			objG.style.opacity=degree/101
  		else
  			tS.disabled=true
  		setTimeout("fadeOutPic(objG)", 50);
  	}
  	else
  	{
  	tS.disabled=true
  		changeImage('pic');
  	}
  	//tS.disabled=true
  }


  function changeImage(id)
  {
  	setTimeout("changeImage(id)", 3000);
  	currImgIdx++;
  	if(currImgIdx >= imgArray.length) currImgIdx = 0;
  	degree = _startDegree;
  	fadeAssist = 0;
  	var picImg = document.getElementById(id);
  	picImg.src = imgArray[currImgIdx];
  	fadeInPic(id);
  }

  function loadFirst(id)
  {
  	fadeInPic(id);
  }

#content
  #header
    #title
      %img{:alt => "AdSlap!It", :src => "/images/title.png"}/
      %img{:alt => "AdSlap!It Tag Line", :height => "40", :src => "/images/TAGline.png", :width => "400"}/
    #logo
      %img{:alt => "adslapit logo", :height => "200", :src => "/images/logo.png", :width => "200"}/
  #main
    #tryit
      %table
        %tr
          %td{:rowspan => "3"}
            %img#pic{:height => "480", :onload => "loadFirst(this)", :src => "images/woman1.jpg", :width => "300"}
          %td
            = link_to image_tag("/images/new_button.png", :style =>"border: 0px; width: 300px"), new_session_path
        %tr
          %td
            = link_to 'View adslaps from startup weekend', startup_weekend_path
        %tr
          %td{:height => "300"}
            Contact:
            %br
            %a{:href => "mailto:zach@talamu.com"} zach@talamu.com
            %br
            %br
            Team:
            %br
            Zach Goodman
            %br
            Keith Chen
            %br
            Shawn Chen
            %br
            Josiah Barnes
            %br
            Nathan Kwadade
            %br
            Mary Nichols
            %br
            Davis Allen
  #footer
    Copyright 2011  AdSlap!It