config/routes.rb
Adslapme::Application.routes.draw do

  resources :users
  resources :albums do
    collection do
      get :import_facebook_photos
    end
  end
  resources :pictures

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  
  match '/submit_pic',  :to => 'users#submit_pic'
  match '/capture_pic',  :to => 'users#capture_pic'
  match '/startup_weekend',  :to => 'users#show_sw_pics'
  

  root :to => 'pages#home'

  resources :sessions, :only => [:new, :create] do
    collection do
      get :facebook_session_create
    end
  end

end

app/models/album.rb
class Album < ActiveRecord::Base

  has_many :pictures
  belongs_to :user

  validates_uniqueness_of :uid

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.xml
  def index
    @albums = current_user.albums
    @album = current_user.albums.first
    @pictures = @album.pictures
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @albums }
    end
  end
  
  def import_facebook_photos
    
    @graph = current_user.facebook_graph

    @albums = @graph.get_connections("me", "albums")

    @albums.each do |a|
      album = current_user.albums.build(:uid => a["id"], :cover_photo_id => a["cover_photo"])
      album.save
      @pictures = @graph.get_connections(a["id"], "photos")
      @pictures.each do |p|
        picture = album.pictures.build(:uid => p["id"], :thumb_url => p["picture"], :source_url => p["source"])
        picture.save
      end
    end
    
    redirect_to albums_path

  end

  # GET /albums/1
  # GET /albums/1.xml
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.xml
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.xml
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to(@album, :notice => 'Album was successfully created.') }
        format.xml  { render :xml => @album, :status => :created, :location => @album }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.xml
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to(@album, :notice => 'Album was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.xml
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to(albums_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :cover_photo_id %><br />
    <%= f.text_field :cover_photo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.haml
:javascript
  var _featherLoaded = false;

  Feather_Theme = 'bluesky';
  Feather_EditOptions = 'all';
  Feather_OpenType = 'lightbox';
  Feather_MaxSize = '480';
  Feather_CropSizes = '320x240,640x480,800x600,1280x1024';

   Feather_Stickers = [ ["http://www.emoticonswallpapers.com/avatar/logos/Doritos.gif", "http://www.emoticonswallpapers.com/avatar/logos/Doritos.gif"] ];

  Feather_OnSave = function(id, url) {
      aviaryeditor_close();
      window.location = "#{Settings.app_url}/submit_pic/?url=" + url
  }

  Feather_OnLoad = function() {
      _featherLoaded = true;
  }

  function launchEditor(imageid, src) {
        if (_featherLoaded) {
            aviaryeditor(imageid, src);
        }
    }
%script{:src => "http://feather.aviary.com/js/feather.js", :type => "text/javascript"}
%h1 Listing albums
- @pictures.each do |p|
  %p
    <input type = "image" src=#{p.thumb_url} value="Edit photo" onclick="launchEditor(this, '#{"#{p.source_url}"}'); return false;" />
%table
  - @albums.each do |album|
    %tr
      %td= album.uid
      %td= album.user_id
      %td= album.cover_photo_id
      %td= link_to 'Show', album
      %td= link_to 'Edit', edit_album_path(album)
      %td= link_to 'Destroy', album, :confirm => 'Are you sure?', :method => :delete
= link_to 'New Album', new_album_path

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uid:</b>
  <%= @album.uid %>
</p>

<p>
  <b>User:</b>
  <%= @album.user_id %>
</p>

<p>
  <b>Cover photo:</b>
  <%= @album.cover_photo_id %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>